#pragma once
#ifndef GROUPS_H
#define GROUPS_H

enum Groups {
	BROWN, LTBLUE, PURPLE, ORANGE, RED, YELLOW, GREEN, BLUE, LUX_TAX, INC_TAX,STATION,UTIL,
	FREE_PARKING, VISIT_JAIL, GO_JAIL, START,CHEST,CHANCE
};
#endif // !GROUPS_H
